# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RuterPilot_WIP' do
	pod 'RuterGOSDK', :git => 'https://stash.ruter.no/scm/nex/rutergo-sdk-ios.git', :branch => 'master'
	pod 'GeodeticUTMConverter'
  	pod 'SwiftKeychainWrapper'

  	pod 'Firebase/Core'
  	pod 'Firebase/Crash'
  	pod 'Firebase/Database'
  	pod 'Firebase/RemoteConfig'
  	pod 'GoogleTagManager', '~> 5.0'

  	pod 'AWSCore'
  	pod 'AWSCognito'
  	pod 'AWSKinesis'

	pod 'Intercom'
	pod 'Instabug'
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RuterPilot_WIP

end
